name: "MS Teams notify (internal)"
description: "Post a message to Microsoft Teams via webhook"
inputs:
  webhook_url:
    required: true
    description: "Teams webhook URL"
  title:
    required: false
    default: "GitHub Actions"
  message:
    required: true
  color:
    required: false
    default: "2EB886" # green
  button_text:
    required: false
    default: "View run"
  button_url:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Post to Teams
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        TITLE: ${{ inputs.title }}
        MESSAGE: ${{ inputs.message }}
        COLOR: ${{ inputs.color }}
        BUTTON_TEXT: ${{ inputs.button_text }}
        BUTTON_URL: ${{ inputs.button_url }}
      run: |
        set -euo pipefail

        if [ -n "${BUTTON_URL}" ]; then
          ACTIONS=$(cat <<EOF
        [{
        "@type": "OpenUri",
        "name": "${BUTTON_TEXT}",
        "targets": [{ "os": "default", "uri": "${BUTTON_URL}" }]
        }]
        EOF
        )
        else
          ACTIONS="[]"
        fi

        payload=$(cat <<EOF
        {
        "@type": "MessageCard",
        "@context": "https://schema.org/extensions",
        "themeColor": "${COLOR}",
        "summary": "${TITLE}",
        "title": "${TITLE}",
        "text": "${MESSAGE}",
        "potentialAction": ${ACTIONS}
        }
        EOF
        )

        curl -sS -X POST -H "Content-Type: application/json" --data "$payload" "$WEBHOOK_URL"
