name: Generate release tag

on:
  workflow_call:
    outputs:
      release_tag:
        description: 'The unique release tag'
        value: ${{ jobs.generate-tag.outputs.release_tag }}

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.vars.outputs.release_tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get ARM Access Token
        run: |
          RESPONSE=$(curl -s -X POST \
            "https://bridge-m2m-prod.auth.us-east-1.amazoncognito.com/oauth2/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -u "${{ secrets.COGNITO_CLIENT_ID }}:${{ secrets.COGNITO_CLIENT_SECRET }}" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "scope=bridge-api/arm-admin bridge-api/arm-register-release bridge-api/arm-request-approval")

          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
            echo "Failed to obtain access token"
            echo "$RESPONSE"
            exit 1
          fi

          echo "ARM_TOKEN=$TOKEN" >> $GITHUB_ENV
      
      - name: Register Release
        run: |
          curl -X POST \
            "https://att0c36204.execute-api.us-east-1.amazonaws.com/prod/arm/register/release" \
            -H "Authorization: Bearer $ARM_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "application_name": "Glow-Portals",
              "arm_environment": "PROD",
              "requested_by": "kiran",
              "servicenow_change": {
                "planned_startdate": "2026-07-31T10:00:00Z",
                "planned_enddate": "2026-07-31T10:30:00Z",
                "time_zone": "Europe/Amsterdam",
                "users_affected": "<1000",
                "short_description": "A mock release",
                "description": "A detailed description of the release.",
                "implementation_plan": "implementation plan",
                "test_plan": "test plan",
                "backout_plan": "backout plan",
                "risk_impact_analysis": "Risk impact analysis"
              }
            }'
      # - name: Validate input
      #   id: vars
      #   run: |
      #         response=$(curl -X POST \
      #         -H "Content-Type: application/json" \
      #         https://yfoa5flvfk.execute-api.us-east-1.amazonaws.com/staging/generate-release-id \
      #         -d '{
      #             "platform": "github",
      #             "env": "prod",
      #             "repo": "${{ github.event.repository.name }}"
      #         }')
      #         echo "Response: $response"
      #         status=$(echo "$response" | jq -r '.status')
      #         if [ "$status" -ne 200 ]; then
      #           echo "Error: API call failed with status $status"
      #           exit 1
      #         fi
      #         release_id=$(echo "$response" | jq -r '.release_id')
      #         echo "Generated release ID: $release_id"
      #         echo "release_tag=$release_id" >> $GITHUB_OUTPUT
      #       # FULL_HASH=$(git rev-parse --short HEAD)
      #       # UNIQUE_ID=_${{ github.run_id }}
            
      #       # echo "release_tag=$FULL_HASH$UNIQUE_ID" >> $GITHUB_OUTPUT

