name: Get last successful workflow run

on:
  workflow_dispatch:

jobs:
    workflow-runs:
        runs-on: ubuntu-latest
        steps:
            - name: Dispatch chart tagger event
              run: |
                curl -L \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.CLASSIC_PAT_CROSS_REPO }}" \
                    -H "X-GitHub-Api-Version: 2026-03-10" \
                    https://api.github.com/repos/vkirankumar/portal-glow-mock/actions/workflows/deploy-to-prod.yaml/runs
